#pragma once

#include <Arduino.h>
#include <math.h>

// Auto-generated by src/experiments/export_embedded_model.py.
// The model is a compact binary Logistic Regression baseline for ESP32/Wokwi
// demonstration. It is not the full LightGBM IDS baseline.

constexpr int IDS_FEATURE_COUNT = 10;
constexpr int IDS_SAMPLE_COUNT = 8;
constexpr float IDS_QUANTIZATION_SCALE = 4011.43171467f;
constexpr float IDS_THRESHOLD = 0.5f;

const char *IDS_FEATURE_NAMES[IDS_FEATURE_COUNT] = {"src_port", "dst_port", "duration", "src_bytes", "dst_bytes", "missed_bytes", "src_pkts", "src_ip_bytes", "dst_pkts", "dst_ip_bytes"};

const float IDS_MEANS[IDS_FEATURE_COUNT] = {38651.65028963, 3498.82386249, 8.37929102, 263951.18002890, 238500.61886231, 40595.89272895, 9.63448121, 789.30461874, 3.70108509, 1179.34912399};
const float IDS_SCALES[IDS_FEATURE_COUNT] = {19294.73812862, 10199.42153027, 621.84072557, 17447545.23612135, 15928602.82619206, 5817083.93568970, 92.53332156, 23466.73222955, 328.36355050, 28023.89666932};
const int16_t IDS_WEIGHTS_Q[IDS_FEATURE_COUNT] = {283, -1409, -206, 944, 490, 435, -14891, 30000, -953, 1571};
const int16_t IDS_INTERCEPT_Q = 497;

const float IDS_TEST_SAMPLES[IDS_SAMPLE_COUNT][IDS_FEATURE_COUNT] = {
  {37472.000000, 53.000000, 0.000000, 0.000000, 0.000000, 0.000000, 1.000000, 59.000000, 0.000000, 0.000000},
  {49658.000000, 53.000000, 0.000059, 130.000000, 0.000000, 0.000000, 2.000000, 186.000000, 0.000000, 0.000000},
  {80.000000, 1412.000000, 0.168473, 0.000000, 0.000000, 0.000000, 120.000000, 4800.000000, 0.000000, 0.000000},
  {15100.000000, 53.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 1.000000, 292.000000},
  {33110.000000, 80.000000, 0.002565, 155.000000, 651.000000, 0.000000, 5.000000, 423.000000, 5.000000, 919.000000},
  {49432.000000, 80.000000, 0.000115, 0.000000, 0.000000, 0.000000, 1.000000, 48.000000, 1.000000, 40.000000},
  {4444.000000, 49218.000000, 0.000000, 0.000000, 0.000000, 0.000000, 1.000000, 168.000000, 0.000000, 0.000000},
  {37926.000000, 80.000000, 0.435328, 243.000000, 1919.000000, 0.000000, 4.000000, 459.000000, 5.000000, 2179.000000}
};

const int IDS_TEST_LABELS[IDS_SAMPLE_COUNT] = {0, 0, 0, 0, 1, 1, 1, 1};

inline float idsSigmoid(float value) {
  if (value >= 0.0f) {
    float z = expf(-value);
    return 1.0f / (1.0f + z);
  }
  float z = expf(value);
  return z / (1.0f + z);
}

inline float idsPredictProbability(const float features[IDS_FEATURE_COUNT]) {
  float score = static_cast<float>(IDS_INTERCEPT_Q) / IDS_QUANTIZATION_SCALE;
  for (int i = 0; i < IDS_FEATURE_COUNT; i++) {
    float normalized = (features[i] - IDS_MEANS[i]) / IDS_SCALES[i];
    float weight = static_cast<float>(IDS_WEIGHTS_Q[i]) / IDS_QUANTIZATION_SCALE;
    score += weight * normalized;
  }
  return idsSigmoid(score);
}

inline int idsPredictClass(const float features[IDS_FEATURE_COUNT]) {
  return idsPredictProbability(features) >= IDS_THRESHOLD ? 1 : 0;
}

constexpr float IDS_EXPORT_ACCURACY = 0.81797721f;
constexpr float IDS_EXPORT_F1 = 0.88884388f;
constexpr float IDS_EXPORT_MACRO_F1 = 0.69332710f;
